<a href="https://colab.research.google.com/github/Abhimanyu-0/Python-DL_Tensorflow/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamental concepts of Tensors


* Introduction to tensors. 
* Getting information from tensors.
* Manipulating Tensors
* Tensors and NumPY 
* Using tf. function 
* Using GPUs with TensorFlow(or TPUs)
* Exercises 


## Introduction to Tensors

In [1]:
# Import TensorFlow 
import tensorflow as tf 
print(tf.__version__)


2.7.0


In [2]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor 
scalar.ndim

0

In [4]:
# Create a vector 
vector = tf.constant([10 ,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector 
vector.ndim

1

In [6]:
# Create a matrix 
matrix = tf.constant([[10,7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim 

2

In [8]:
 # Create another matrix 
 another_matrix =  tf.constant([[10.,7.],
                                [3.,2.],
                                [8.,9.]], dtype = tf.float16)
 another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim 

2

In [10]:
# Create a tensor 
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor 


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [11]:
tensor.ndim

3

## Creating tensors with tf.Variable

In [12]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:

# how about .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Change unchangeable tensor 
unchangeable_tensor[0].assign(7)
unchangeable_tensor
# Doing this gives an error because the tensor is supposed to be unchangeable

AttributeError: ignored

Note: TensorFlow does the assignment for you (variable or constant). 
However when in doubt, use tf.constant and change it later. 


### Creating Random Tensors 

- Random tensors are tensors of arbitrary size filled with random numbers


In [17]:
#Create two random (but same) tensors 
random_1  = tf.random.Generator.from_seed(42)   
random_1 = random_1.normal(shape = (2,3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (2,3))

# equal?
random_1
random_2
random_1 ==random_2

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

### Shuffle the order of elements in a tensor

In [18]:
# shuffle a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [19]:
# shuffle our non_shuffled tensor

tf.random.set_seed(32) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

### For more information on how global seed and operation seed works:
* refer https://www.tensorflow.org/api_docs/python/tf/random/set_seed

Point:
* If we want our shuffled tensors to be in the same order, we have to use both global and operation seed.

### Other ways to make tensors 


In [20]:
tf.ones([2,5]) # tensor of all ones of shape[2,5]

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# Create a tensor of all zeroes 
tf.zeros([2,5])

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors 

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU computing 

In [22]:
# NumPy arrays to tensors 

import numpy as np
A = np.arange(1,25, dtype = np.int32)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
tensor_A = tf.constant(A, shape=(2,3,4))
A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

- A is now converted into a tensor 
- The shape (2,3,4) can be used because 2*3*4= 24 which is the shape of the original array

Now, we wil try (2,3,5) and see what happens!

In [24]:
tensor_A = tf.constant(A, shape= (2,3,5))

TypeError: ignored

- We get an error because the multiplication of the numbers is 30 which is greater than the original shape of the array.

In [ ]:
# Creating a random array 
X = np.random.randn(12,6)
X

# Convert into tensor
X_tens = tf.constant(X, shape=(2,18,2))
X_tens
tf.size(X_tens)

### Getting information from tensors 
Important attributes

* Shape
* Rank
* Dimension 
* Size 

In [25]:
 # Rank 4 tensor (number of dimentions=4)
 rank_4_tens = tf.zeros(shape=[2,3,4,5])
 rank_4_tens

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tens[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
rank_4_tens.shape, rank_4_tens.ndim, tf.size(rank_4_tens)
# size= number of elements in the tensor

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Practise example

In [28]:
# Get various attributes of our tensor 
print("Datatype of every element:", rank_4_tens.dtype) 
print("Number of dimensions:", rank_4_tens.ndim)
print("Shape of the tensor:", rank_4_tens.shape)
print("Elements along 0 axis:", rank_4_tens.shape[0])
print("Elements along the last axis:", rank_4_tens.shape[-1])
print("Number of elements in our tensor:", tf.size(rank_4_tens))

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of the tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


### Indexing tensors 
Tensors can be indexed just like Python lists 

In [29]:
# Get the first 2 elements of each dimension 
rank_4_tens[:2,:2,:2,:2] 

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [30]:
# Get the first element from each dimension from each index except for the final one
rank_4_tens[:1,:1,:1,:]




<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
# Create a rank 2 tensors(2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [2,5]])
rank_2_tensor.shape 


TensorShape([2, 2])

In [32]:
# Get the last item of each row of our rank 2 tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5], dtype=int32)>

### Adding extra dimension 

In [33]:
# Add extra dimension to our rank 2 tensor 
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 5]]], dtype=int32)>

In [34]:
# Alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor, axis=-1)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

### Manipulating tensors (Tensor operations)

**Basic operations**


In [35]:
# You can add values to a tensor using addition operator 
tensor = tf.constant([[10,7],[2,5]])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 15]], dtype=int32)>

In [36]:
#Original tensor is unchanged 
tensor 


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>

In [37]:
# Multiplication 
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  50]], dtype=int32)>

In [38]:
#Subtraction 
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-8, -5]], dtype=int32)>

In [39]:
# Using the tensorflow built in function 
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 20,  50]], dtype=int32)>

In [40]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [12, 15]], dtype=int32)>

*Use the tensorflow built-in functions to speed up the code

### In Deep learning, matrix multiplication is the most common operation perfomed 


In [41]:
#Matrix multiplication in tensorflow 
print(tensor)
# can drop linalg from tf.linalg.matmul 
tf.matmul(tensor,tensor)


tf.Tensor(
[[10  7]
 [ 2  5]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[114, 105],
       [ 30,  39]], dtype=int32)>

In [42]:
# Practise example
tensor_1 = tf.constant([[1,2,5],
                        [7,2,1],
                        [3,3,3]])
tensor_2 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [43]:
tf.matmul(tensor_2,tensor_1) # matrix dimensions do not match 

InvalidArgumentError: ignored

In [44]:
# Lets change the shape of tensor_1
X = tf.reshape(tensor_2, shape=(2,3))
print(X)

tf.Tensor(
[[3 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32)


In [45]:
tf.matmul(X,tensor_1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[56, 34, 38],
       [38, 40, 60]], dtype=int32)>

In [46]:
tensor_1.shape

TensorShape([3, 3])

In [47]:
# Can do the same with transpose 
tf.transpose(tensor_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

###There is a difference between transpose and reshape function. 
***The transpose function reverses the dimensions(Flips the axes)**
***The reshape function changes the shape but in order of the matrix elements**

### Changing the datatype of tensors

In [48]:
A = tf.constant([[2,3],[3,7]])

In [49]:
A.dtype

tf.int32

In [50]:
 # changing from int32 to int16
 A = tf.cast(A, dtype = tf.int16)
 A

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[2, 3],
       [3, 7]], dtype=int16)>

In [51]:
# Changing from int16 to float32 
A = tf.cast(A, dtype = tf.float32)
A

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 7.]], dtype=float32)>

### Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values 

In [54]:
# Get the absolute values 
A = tf.constant([-3,5])
A

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3,  5], dtype=int32)>

In [55]:
#Absolute values 
tf.abs(A)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

Forms of aggregation:

*Min
*Max
*Mean
*Sum
(of tensors)

In [56]:
# Random tensor with values between 0 and 100 of size 50 
B = tf.constant(np.random.randint(0,100, size= 50))
B

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([92, 98, 31, 44, 44, 84, 58, 44, 77,  8, 90, 96, 71, 75, 45, 27, 23,
       31,  7, 77, 16, 96, 49, 22, 11, 57, 81, 61, 96, 52, 16, 47, 65, 98,
       82,  1, 64, 13, 36, 16, 91, 96, 92, 82,  7, 38, 73,  6, 37, 30])>

In [58]:
B.shape


TensorShape([50])

In [59]:
B.ndim 

1

In [88]:
B = tf.cast(B, dtype= tf.float16)

In [89]:
# Find the minimum 
tf.reduce_min(B)

<tf.Tensor: shape=(), dtype=float16, numpy=1.0>

In [90]:
#Find the max
tf.reduce_max(B)

<tf.Tensor: shape=(), dtype=float16, numpy=98.0>

In [91]:
# Find the sum 
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=float16, numpy=53.03>

In [92]:
# Find the sum 
tf.reduce_sum(B)

<tf.Tensor: shape=(), dtype=float16, numpy=2652.0>

In [93]:

import tensorflow_probability as tfp # Need to import this library to find the variance of a tensor 
tfp.stats.variance(B)

<tf.Tensor: shape=(), dtype=float16, numpy=945.5>

In [96]:
tfp.stats.stddev(B) # Needed to cast this tensor from integer to float for this to work '



<tf.Tensor: shape=(), dtype=float16, numpy=30.75>

### Find the positional maximum and minimum 

In [100]:
# Create  a new tensor for finding positional max and min 
tf.random.set_seed(32)
F = tf.random.normal(shape=[50])

In [106]:
# Find the max
tf.math.argmax(
    F, output_type=tf.dtypes.int64, name=None
) 

<tf.Tensor: shape=(), dtype=int64, numpy=21>

In [104]:
# Index on our largest value position 
F[(tf.argmax(F))]

<tf.Tensor: shape=(), dtype=float32, numpy=2.1947155>

In [107]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([ 0.82033765,  0.73500305,  1.0454717 ,  0.702631  , -0.25499234,
        0.11062323, -0.3612894 ,  1.2916003 ,  0.3403678 , -1.0334859 ,
       -2.2145016 ,  1.8804389 , -1.0951902 ,  1.7431897 , -2.221157  ,
       -2.1462772 , -0.07038584,  0.6324103 ,  2.112939  ,  1.0148501 ,
       -0.63394046,  2.1947155 ,  0.714509  , -0.7364685 ,  0.30649456,
       -0.15495203, -1.9615371 , -1.4596082 , -0.19631572,  0.04369557,
        0.62514496, -0.01595836,  1.617205  ,  0.69181174, -0.9558919 ,
       -1.5583311 , -0.39606905, -1.1966665 , -0.62148017, -1.7329216 ,
       -0.7031746 , -0.3945389 , -0.07296715, -1.2289966 , -0.50324875,
       -0.84059316, -0.5273051 ,  0.6049654 ,  0.02152216,  0.8359321 ],
      dtype=float32)>

In [108]:
# Find the min 
tf.argmin(F)


<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [109]:
# Now we have the index as 14 
# We can now find the number at that index 
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=-2.221157>

### Squeezing a tensor(removing all single dimensions)

In [113]:
# Create a tensor 
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=(1,1,1,1,50)))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [114]:
G.shape 

TensorShape([1, 1, 1, 1, 50])

In [119]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape
# Squeezing removes 1

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### one hot encoding tensors 

In [127]:
# create a list 
list_1 = [0,1,2,3]
depth = 4
# one hot encode 
tf.one_hot(list_1, depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [128]:
# Specify custom values for one hot encoding 
tf.one_hot(list_1, depth, on_value="YES", off_value= "NO")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'YES', b'NO', b'NO', b'NO'],
       [b'NO', b'YES', b'NO', b'NO'],
       [b'NO', b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'NO', b'YES']], dtype=object)>

### Squaring, log, square root

In [129]:
# Create a new tensor 
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [130]:
tf.square(H) #Find the square 

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [136]:
# Find the square root ( will show error if we input int, this method requires float)
tf.sqrt(tf.cast(H,dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [141]:
# Find the log 
tf.math.log(tf.cast(H,dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

In [142]:
# Create a tensor directly from a numpy array 
X = tf.constant(np.array([3.,5.,11,]))
X

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  5., 11.])>

In [143]:
# convert tensor back into NumPy array 
np.array(X)

array([ 3.,  5., 11.])

In [144]:
# Convert tensor J into NumPy array 
X.numpy()

array([ 3.,  5., 11.])

In [148]:
X = tf.constant([2.])
X.numpy()[0]

2.0

In [149]:
# Default types of each are slightly different
numpy_X = tf.constant(np.array([2,4,6,8]))
tensor_X = tf.constant([2,4,6,8])

# Check datatypes of each 
numpy_X.dtype, tensor_X.dtype


(tf.int64, tf.int32)