<a href="https://colab.research.google.com/github/Abhimanyu-0/Python-DL_Tensorflow/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamental concepts of Tensors


* Introduction to tensors. 
* Getting information from tensors.
* Manipulating Tensors
* Tensors and NumPY 
* Using tf. function 
* Using GPUs with TensorFlow(or TPUs)
* Exercises 


## Introduction to Tensors

In [2]:
# Import TensorFlow 
import tensorflow as tf 
print(tf.__version__)


2.7.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor 
scalar.ndim

0

In [ ]:
# Create a vector 
vector = tf.constant([10 ,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector 
vector.ndim

1

In [ ]:
# Create a matrix 
matrix = tf.constant([[10,7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim 

2

In [ ]:
 # Create another matrix 
 another_matrix =  tf.constant([[10.,7.],
                                [3.,2.],
                                [8.,9.]], dtype = tf.float16)
 another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim 

2

In [ ]:
# Create a tensor 
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor 


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## Creating tensors with tf.Variable

In [ ]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:

# how about .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Change unchangeable tensor 
unchangeable_tensor[0].assign(7)
unchangeable_tensor
# Doing this gives an error because the tensor is supposed to be unchangeable

AttributeError: ignored

Note: TensorFlow does the assignment for you (variable or constant). 
However when in doubt, use tf.constant and change it later. 


### Creating Random Tensors 

- Random tensors are tensors of arbitrary size filled with random numbers


In [ ]:
#Create two random (but same) tensors 
random_1  = tf.random.Generator.from_seed(42)   
random_1 = random_1.normal(shape = (2,3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (2,3))

# equal?
random_1
random_2
random_1 ==random_2

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

### Shuffle the order of elements in a tensor

In [5]:
# shuffle a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [19]:
# shuffle our non_shuffled tensor

tf.random.set_seed(32) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

### For more information on how global seed and operation seed works:
* refer https://www.tensorflow.org/api_docs/python/tf/random/set_seed

Point:
* If we want our shuffled tensors to be in the same order, we have to use both global and operation seed.

### Other ways to make tensors 


In [21]:
tf.ones([2,5]) # tensor of all ones of shape[2,5]

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
# Create a tensor of all zeroes 
tf.zeros([2,5])

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors 

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU computing 

In [25]:
# NumPy arrays to tensors 

import numpy as np
A = np.arange(1,25, dtype = np.int32)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [27]:
tensor_A = tf.constant(A, shape=(2,3,4))
A


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

- A is now converted into a tensor 
- The shape (2,3,4) can be used because 2*3*4= 24 which is the shape of the original array

Now, we wil try (2,3,5) and see what happens!

In [28]:
tensor_A = tf.constant(A, shape= (2,3,5))

TypeError: ignored

- We get an error because the multiplication of the numbers is 30 which is greater than the original shape of the array.

### Getting information from Tensors

In [39]:
# Creating a random array 
X = np.random.randn(12,6)
X

# Convert into tensor
X_tens = tf.constant(X, shape=(2,18,2))
X_tens

<tf.Tensor: shape=(2, 18, 2), dtype=float64, numpy=
array([[[-1.31800867e+00,  3.24841280e+00],
        [-5.64164102e-01, -2.07564572e+00],
        [ 1.48293626e+00,  7.96855860e-01],
        [-4.54560153e-01,  2.10724546e+00],
        [ 9.92569852e-02, -1.57343485e+00],
        [ 4.93370941e-01,  1.82122471e+00],
        [-3.74393345e-01,  2.05251885e+00],
        [-7.32628129e-01, -1.18472028e+00],
        [-1.11574833e-01,  4.54819469e-01],
        [-7.37565772e-01, -8.03453962e-01],
        [-4.07930343e-01, -1.07604703e+00],
        [ 9.15510050e-01, -1.54520447e+00],
        [ 6.00452856e-01,  1.57148314e+00],
        [-2.42207194e-01, -8.83989473e-01],
        [ 1.51233853e+00,  4.29393286e-01],
        [ 2.67493837e-01, -7.04438332e-01],
        [ 1.08386245e+00, -2.09425214e-01],
        [-8.59412507e-01, -1.59448618e+00]],

       [[-1.11890317e+00, -1.69003161e+00],
        [ 1.42978865e+00, -1.09307583e+00],
        [-3.13336420e-01, -1.04145566e+00],
        [ 6.87883419e-