<a href="https://colab.research.google.com/github/Abhimanyu-0/Python-DL_Tensorflow/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamental concepts of Tensors


* Introduction to tensors. 
* Getting information from tensors.
* Manipulating Tensors
* Tensors and NumPY 
* Using tf. function 
* Using GPUs with TensorFlow(or TPUs)
* Exercises 


## Introduction to Tensors

In [1]:
# Import TensorFlow 
import tensorflow as tf 
print(tf.__version__)


2.7.0


In [2]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor 
scalar.ndim

0

In [4]:
# Create a vector 
vector = tf.constant([10 ,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector 
vector.ndim

1

In [6]:
# Create a matrix 
matrix = tf.constant([[10,7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim 

2

In [8]:
 # Create another matrix 
 another_matrix =  tf.constant([[10.,7.],
                                [3.,2.],
                                [8.,9.]], dtype = tf.float16)
 another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim 

2

In [10]:
# Create a tensor 
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor 


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [11]:
tensor.ndim

3

## Creating tensors with tf.Variable

In [12]:
# Create the same tensor with tf.variable() as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:

# how about .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# Change unchangeable tensor 
unchangeable_tensor[0].assign(7)
unchangeable_tensor
# Doing this gives an error because the tensor is supposed to be unchangeable

AttributeError: ignored

Note: TensorFlow does the assignment for you (variable or constant). 
However when in doubt, use tf.constant and change it later. 


### Creating Random Tensors 

- Random tensors are tensors of arbitrary size filled with random numbers


In [15]:
#Create two random (but same) tensors 
random_1  = tf.random.Generator.from_seed(42)   
random_1 = random_1.normal(shape = (2,3))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (2,3))

# equal?
random_1
random_2
random_1 ==random_2

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

### Shuffle the order of elements in a tensor

In [16]:
# shuffle a tensor
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [17]:
# shuffle our non_shuffled tensor

tf.random.set_seed(32) #global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

### For more information on how global seed and operation seed works:
* refer https://www.tensorflow.org/api_docs/python/tf/random/set_seed

Point:
* If we want our shuffled tensors to be in the same order, we have to use both global and operation seed.

### Other ways to make tensors 


In [ ]:
tf.ones([2,5]) # tensor of all ones of shape[2,5]

In [ ]:
# Create a tensor of all zeroes 
tf.zeros([2,5])

### Turn NumPy arrays into tensors 

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU computing 

In [19]:
# NumPy arrays to tensors 

import numpy as np
A = np.arange(1,25, dtype = np.int32)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
tensor_A = tf.constant(A, shape=(2,3,4))
A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

- A is now converted into a tensor 
- The shape (2,3,4) can be used because 2*3*4= 24 which is the shape of the original array

Now, we wil try (2,3,5) and see what happens!

In [21]:
tensor_A = tf.constant(A, shape= (2,3,5))

TypeError: ignored

- We get an error because the multiplication of the numbers is 30 which is greater than the original shape of the array.

In [22]:
# Creating a random array 
X = np.random.randn(12,6)
X

# Convert into tensor
X_tens = tf.constant(X, shape=(2,18,2))
X_tens
tf.size(X_tens)

<tf.Tensor: shape=(), dtype=int32, numpy=72>

### Getting information from tensors 
Important attributes

* Shape
* Rank
* Dimension 
* Size 

In [23]:
 # Rank 4 tensor (number of dimentions=4)
 rank_4_tens = tf.zeros(shape=[2,3,4,5])
 rank_4_tens

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tens[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
rank_4_tens.shape, rank_4_tens.ndim, tf.size(rank_4_tens)
# size= number of elements in the tensor

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Practise example

In [30]:
# Get various attributes of our tensor 
print("Datatype of every element:", rank_4_tens.dtype) 
print("Number of dimensions:", rank_4_tens.ndim)
print("Shape of the tensor:", rank_4_tens.shape)
print("Elements along 0 axis:", rank_4_tens.shape[0])
print("Elements along the last axis:", rank_4_tens.shape[-1])
print("Number of elements in our tensor:", tf.size(rank_4_tens))

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of the tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


### Indexing tensors 
Tensors can be indexed just like Python lists 

In [31]:
# Get the first 2 elements of each dimension 
rank_4_tens[:2,:2,:2,:2] 

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
# Get the first element from each dimension from each index except for the final one
rank_4_tens[:,:1,:1,:1]




<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [40]:
# Create a rank 2 tensors(2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [2,5]])
rank_2_tensor.shape 


TensorShape([2, 2])

In [43]:
# Get the last item of each row of our rank 2 tensor 
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5], dtype=int32)>

### Adding extra dimension 

In [45]:
# Add extra dimension to our rank 2 tensor 
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 5]]], dtype=int32)>

In [46]:
# Alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor, axis=-1)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5]], dtype=int32)>