<a href="https://colab.research.google.com/github/Abhimanyu-0/Python-DL_Tensorflow/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamental concepts of Tensors


* Introduction to tensors. 
* Getting information from tensors.
* Manipulating Tensors
* Tensors and NumPY 
* Using tf. function 
* Using GPUs with TensorFlow(or TPUs)
* Exercises 


## Introduction to Tensors

In [ ]:
# Import TensorFlow 
import tensorflow as tf 
print(tf.__version__)


2.7.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor 
scalar.ndim

0

In [ ]:
# Create a vector 
vector = tf.constant([10 ,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector 
vector.ndim

1

In [ ]:
# Create a matrix 
matrix = tf.constant([[10,7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim 

2

In [ ]:
 # Create another matrix 
 another_matrix =  tf.constant([[10.,7.],
                                [3.,2.],
                                [8.,9.]], dtype = tf.float16)
 another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim 

2

In [ ]:
# Create a tensor 
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor 


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## Creating tensors with tf.Variable